<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DynamicExpresso.Core" Version="2.19.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.12" />
    <PackageVersion Include="Sodium.Core" Version="1.3.4" />
    <PackageVersion Include="Terminal.Gui" Version="1.19.0" />
  </ItemGroup>
</Project>
